//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string NewsTitle { get; set; }
        public string NewsSlug { get; set; }
        public string NewsContents { get; set; }
        public System.Guid PostedBy { get; set; }
        public System.DateTime PostedDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Administrator Administrator { get; set; }

        public bool IsDeleted { get { return DeleteDate == null; }}
    }
}
