//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.AlbumGeneres = new HashSet<AlbumGenere>();
            this.Tracks = new HashSet<Track>();
        }
    
        public System.Guid AlbumID { get; set; }
        public string AlbumTitle { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string AlbumCoverPath { get; set; }
        public bool IsActive { get; set; }
        public System.Guid UserID { get; set; }
    
        public virtual SiteUser SiteUser { get; set; }
        public virtual ICollection<AlbumGenere> AlbumGeneres { get; set; }
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
