//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumGenere
    {
        public int Id { get; set; }
        public System.Guid AlbumID { get; set; }
        public int GenereID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Genere Genere { get; set; }
    }
}
