//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharingType
    {
        public SharingType()
        {
            this.UserTrackShares = new HashSet<UserTrackShare>();
        }
    
        public int SharingTypeID { get; set; }
        public string SharingTypeDetail { get; set; }
    
        public virtual ICollection<UserTrackShare> UserTrackShares { get; set; }
    }
}
