//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.TrackGeneres = new HashSet<TrackGenere>();
            this.UserTrackShares = new HashSet<UserTrackShare>();
        }
    
        public System.Guid TrackID { get; set; }
        public string TrackTitle { get; set; }
        public System.Guid AlbumID { get; set; }
        public string TrackPath { get; set; }
        public string TrackCoverPath { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsActive { get; set; }
        public System.Guid UserID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual SiteUser SiteUser { get; set; }
        public virtual ICollection<TrackGenere> TrackGeneres { get; set; }
        public virtual ICollection<UserTrackShare> UserTrackShares { get; set; }

        public virtual int LikesCount { get; set; }
    }
}
