//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTrackShareLike
    {
        public int UserTrackShareLikeID { get; set; }
        public int UserTrackShareID { get; set; }
        public System.Guid LikedBy { get; set; }
    
        public virtual SiteUser SiteUser { get; set; }
        public virtual UserTrackShare UserTrackShare { get; set; }
    }
}
