//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddressType
    {
        public UserAddressType()
        {
            this.UserAddresses = new HashSet<UserAddress>();
        }
    
        public int UserAddressTypeID { get; set; }
        public string UserAddressTypeDetail { get; set; }
    
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
    }
}
